### ISSUE TITLE
Iphone 5/5s gyro drift

### ISSUE THREAD

**Issue by iRomano** [borismus/webvr-polyfill#30]
Hi

I'm using ComplementaryOrientation, from your sample (https://github.com/borismus/webvr-polyfill/tree/master/fusion)
But i have an error with iPhone 5/5S, gyro is drift.

 If you were to place your phone flat and capture it's gyro-based position, then pick it up, rotate it a bunch, and place it flat again, its integrated gyro position might be quite different from what it was before.

**Comment by borismus** [comment]
This is not surprising. The problem complimentary orientation filter is
solving is not drift in general, but the visible drift caused by using the
magnetometer indiscriminately. In this case, you hold your cardboard still
and the world moves anyway.  See my blog post about it.

**Comment by iRomano** [comment]
Hi
I read your article: http://smus.com/sensor-fusion-prediction-webvr/
And i used fusion - ComplementaryOrientation, prediction. 
Maybe I poorly explained my problem.
If you pick up the phone and rotate it, then put in the original value, the value of event.alpha is another.
I found the event: event.webkitCompassHeading
Maybe it used to calibrate?
Is ComplementaryOrientation support this event?

**Comment by borismus** [comment]
We do not currently have a fix for long term drift. It might be possible to
use the compass to help solve the problem, but it has to be done very
carefully since the magnetometer is notoriously noisy and unreliable. Even
in native cardboard sdk the problem is unresolved.

If you have ideas for solving the problem, please experiment with them and
send a PR to the polyfill :)

**Comment by giladaya** [comment]
Sorry to bring up an old issue, but unfortunately it's still relevant.

I too am trying to solve the absolute drift issue (which is not only related to iPhones BTW).
In my research, I found that there are several available algorithms intended for 9DOF sensor fusion (EG Mahony, Madgwick).
I'm still trying to wrap my head around the math in these algorithms, but I had to wonder whether my efforts are futile.

Meaning - what was the reason that none of the available algorithms were chosen in implementing the polyfill?  
Were they tested and found to be unsuitable? Too time-consuming to implement? Too processor intensive?

I believe that the answers might save some time in attempts to solve this problem.

**Comment by borismus** [comment]
Absolute drift is a hard problem. My experience with magnetometers in many phones is that they aren't reliable at all. The fusion in this project is pretty basic, but engineers on my team have spent a lot of time, and native implementations are more sophisticated. 

They haven't quite cracked the absolute problem though. If you can improve on the sensor fusion in this project by fusing with magnetometer, very open to accepting PRs. But whatever you want to land would have to go through testing on a bunch of hardware.

**Comment by giladaya** [comment]
I implemented a solution using the new [deviceorientationabsolute](https://developers.google.com/web/updates/2016/03/device-orientation-changes) event, so it currently works only in Chrome for android (>50). For other devices, behavior will not change.
The basic idea is to have a second complementary filter step which fuses the calculated rotation quaternion with the rotation given by deviceorientationabsolute.
This takes care of the drift, but because the magnetometer is laggy, the user may see the scene moving even when her head is not moving. So to prevent this, I used an adaptive fusion factor which is equal to 0 below some radial velocity threshold.
This means that in the short term the user may experience yaw drift, but it should cancel out over time (assuming there will be some head movement)

I'm not sure that it's good enough for a PR, but in case someone finds it useful - it's available in my fork.
