### ISSUE TITLE
fails to initialise if in iframe on Chrome 49 Android 6.0.1

### ISSUE THREAD

**Issue by gmarinov** [borismus/webvr-polyfill#80]
https://github.com/borismus/webvr-polyfill/blob/master/src/viewer-selector.js#L33

if localStorage is unavailable then `this.selectedKey = localStorage ...` fails. 
for our build I've added `this.selectedKey = DEFAULT_VIEWER` to the catch block until a better fix.

![screen shot 2016-04-07 at 16 59 28](https://cloud.githubusercontent.com/assets/14101296/14357808/197196ea-fce2-11e5-9129-65cef015dab3.png)

**Comment by cvan** [comment]
Are you in Incognito Mode?

**Comment by gmarinov** [comment]
i don't think so, @cvan . 
49 on 6.0.1 is the only browser I tested to deny access to localStorage there.

**Comment by borismus** [comment]
Do you have "Block third-party cookies and site data" or something like that enabled?

**Comment by brianchirls** [comment]
Blocking third-party cookies would definitely do this. Or possibly an extension, maybe something like Privacy Badger? I've had third-party cookies blocked on my browser for years, and it's amazing how many sites forget to check for this. But it should be handled, since it's a well-defined, predictable, standard behavior built into the browsers. Same deal [here](https://github.com/muvaster/embed.whatcardboard.com/issues/1).

Maybe it would have been better to have `localStorage` just return empty values rather than throw an error, but that ship has sailed.

**Comment by borismus** [comment]
Ping @gmarinov. More information needed. Are you using some kind of 3rd party blocker?

**Comment by gmarinov** [comment]
no

**Comment by borismus** [comment]
Can't repro without more info.

**Comment by sigmaxipi** [comment]
Whitelisting storageapis.google.com via "Settings -> Advanced -> Content Settings -> Cookies -> Manage Exceptions" fixed this issue for me on desktop Chrome. I was running into the same " Failed to read the 'localStorage' " error in the console.

**Comment by gmarinov** [comment]
Seeing as my answers above maybe did not make this clear enough. 

 - no blockers
 - stock android and chrome from play store
 - no incognito mode
 - javascript is enabled
 - safe browsing enabled
 - cookies allowed except third-party cookies
 - do not track is on

Whitelisting storageapis.google.com by going to "Settings -> Advanced -> Content Settings -> Cookies -> Manage Exceptions", is something I cannot ask of the user. The code itself has no default fallback.

**Comment by bnolan** [comment]
Is it possible to fix webvr-polyfill to allow incognito mode?
